import { createFileRoute } from "@tanstack/react-router";
import { llms } from "fumadocs-core/source/llms";
import { docsSource } from "@/lib/docs-source";

const docsLlms = llms(docsSource);

// Distinct from the existing repo-wide public/llms.txt (registry/API-surface
// data, generated by scripts/build-artifacts.ts) -- this is the prose/guide
// content under /docs/*, sourced live from docsSource so it grows
// automatically as more pages are migrated, with no separate build step.
export const Route = createFileRoute("/docs/llms.txt")({
  server: {
    handlers: {
      // Absolutizes the page links -- docsSource's baseUrl ("/docs") makes
      // index() emit relative ones, fine for in-app rendering but not for a
      // plain-text file a machine fetches with no page context to resolve
      // "/docs/feeds" against. Derived from the request's own origin rather
      // than a hardcoded domain so this works in dev and any deploy target.
      GET: ({ request }) => {
        const { origin } = new URL(request.url);
        const body = docsLlms.index().replace(/\]\(\//g, `](${origin}/`);
        return new Response(body, {
          headers: { "content-type": "text/plain; charset=utf-8" },
        });
      },
    },
  },
});
